import turtle
saim = turtle.Turtle()
saim.color("black","green")
saim.begin_fill()
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.end_fill()
saim.penup()
saim.forward(100)
saim.pendown()
saim.begin_fill()
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.right(90)
saim.forward(100)
saim.end_fill()
turtle.done()